modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
# The modid of the mod
modId="useitemonblockevent_examplemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Use Item On Block Event Examplemod" #mandatory
credits="I hear the Minecraft Mod Development discord channel is the cat's bananas" #optional
authors="Commoble"
description='''
Examplemod for Use Item On Block Event. Not built into the production jar.
'''

